name: build gh-pages

on: [push]

env:
  BUILD_OUTPUT_FOLDER: build_outputs_folder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: build-pages
      run: |-
        python -m pip install pyyaml
        python .github/workflows/build_pages.py
    - name: pub-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ env.BUILD_OUTPUT_FOLDER }}
